# Generated by Django 4.2.7 on 2024-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.TextField(blank=True, max_length=900, null=True)),
                ('imageBanner', models.TextField(blank=True, max_length=900, null=True)),
                ('category', models.TextField(blank=True, max_length=900, null=True)),
                ('actor', models.TextField(blank=True, max_length=1500, null=True)),
                ('genre', models.TextField(blank=True, max_length=900, null=True)),
                ('release', models.TextField(blank=True, max_length=900, null=True)),
                ('language', models.TextField(blank=True, max_length=900, null=True)),
                ('rate', models.TextField(blank=True, max_length=900, null=True)),
                ('fee', models.TextField(blank=True, max_length=900, null=True)),
                ('duration', models.TextField(blank=True, max_length=900, null=True)),
            ],
        ),
    ]
